spring:
    kafka:
        bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            properties:
                specific.avro.reader: true
        properties:
            schema.registry.url: http://localhost:7081


server:
    port: 8083