spring:
    application:
        name: test-service
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081

server:
    port: 8082
